In [1]:
from sympy import linsolve, Matrix, S, Symbol, symbols, linear_eq_to_matrix,\
Eq, zeros, latex
from IPython.display import Latex

# Практическое занятие 5
# Компьютерный практикум по алгебре на Python
## Прямые и плоскости в пространстве. Уравнения прямых и  плоскостей.
1. Общее уравнение плоскости:
$$
Ax+By+Cz+D=0,
$$
коэффициенты $A$, $B$ и $C$ являются координатами вектора нормали (он по определению перпендикулярен плоскости).

2. Пусть $A(x_0,y_0,z_0)$ - фиксированная точка на плоскости $\alpha$, вектор $\bar{n}(n_x,n_y,n_z)$ - нормаль к плоскости $\alpha$, тогда в векторной форме уравнение плоскости $\alpha$ запишется в виде:
$$
\bar{n}\cdot{\overline{MA}}=0,
$$
где $M(x,y,z)$ - произвольная точка на плоскости $\alpha$, ${\overline{MA}}$ - вектор в плоскости $\alpha$, знак $\cdot$ означает скалярное произведение.

3. Пусть $A(x_1,y_1,z_1)$, $B(x_2,y_2,z_2)$ и $C(x_3,y_3,z_3)$ - три точки, определяющие плоскость, тогда уравнение плоскости можно записать в виде:
$$
\left|\begin{matrix}
x-x_1&y-y_1&z-z_1\\
x_2-x_1&y_2-y_1&z_2-z_1\\
x_3-x_1&y_3-y_1&z_3-z_1
\end{matrix}\right|=0
$$
4. Пусть в плоскости лежит точка $A(x_0, y_0, z_0)$ и плоскость параллельна векторам $a_1(x_1, y_1, z_1)$ и  $a_2(x_2, y_2, z_2)$, тогда уравнение плоскости можно записать в виде:
$$
\left|\begin{matrix}
x-x_0& y-y_0& z-z_0\\
x_1& y_1& z_1\\
x_2& y_2& z_2
\end{matrix}\right|=0
$$
### Уравнение прямой в пространстве:
Параметрические уравнения прямой:
$$
\left\{\begin{matrix}
x=x_0+ta_1\\
y=y_0+ta_2\\
z=z_0+ta_3
\end{matrix}\right.
$$
в векторной форме:
$$
X=A+t\bar{a}
$$
$X$ и $A$ - радиус-векторы произвольной точки $X$ и заданной точки $A$, лежащих на прямой с направляющим вектором $\bar{a}(a_1, a_2, a_3)$.

Прямую в пространстве можно задать как линию пересечения двух плоскостей:
$$
\left\{\begin{matrix}
A_1x+B_1y+C_1z+D_1=0\\
A_2x+B_2y+C_2z+D_2=0
\end{matrix}\right.
$$


## Пример 1.
Пусть плоскость $\alpha$ задана общим уравнением
$$
3x+5y-2z+5=0.
$$
Найти точку на плоскости, через которую проходит прямая, заданная уравнениями:
$$
\left\{\begin{matrix}
x=1+3t\\
y=-2+2t\\
z=-t
\end{matrix}\right.
$$
Решим СЛАУ:
$$
\left\{\begin{matrix}
3x+5y-2z+5=0\\
x=1+3t\\
y=-2+2t\\
z=-t
\end{matrix}\right.,
$$
Введем ее в виде списка уравнений, и решим с помощью linsolve()

In [2]:
x, y, z, t = symbols('x y z t')
SLAE = [Eq(3 * x + 5 * y - 2 * z + 5, 0),
        Eq(x, 1 + 3 * t),
        Eq(y, -2 + 2 * t),
        Eq(z, -t)]
res = linsolve(SLAE, x, y, z, t)
display(Latex(fr'\text{{ Решение }}{latex(res)}'))

<IPython.core.display.Latex object>

Выделим координаты $x,y,z$ точки пересечения:

In [3]:
point = Matrix(*res)
display(Latex(fr"""\text{{ Решение в виде матрицы }}
{latex(point[:-1, :].T)}"""))

<IPython.core.display.Latex object>

Проверим выполнение всех условий, подставим полученное решение в левые и правые части уравнений системы, предварительно составим словарь подстановок. Для выделения частей уравнений будем использовать свойства lhs и rhs  в классе Equation.

In [4]:
var_dict = {var_: val_ for var_, val_ in zip((x, y, z, t), point)}
for k, item in enumerate(SLAE):
    print(f'{k + 1}) {item.lhs.subs(var_dict)} =  {item.rhs.subs(var_dict)}')

1) 0 =  0
2) 9/7 =  9/7
3) -38/21 =  -38/21
4) -2/21 =  -2/21


## Пример 2.
Определить, пересекаются ли прямые в пространстве, если одна из них проходит через точки $A(1, 2, 3)$ и $B(-3, 5, 0)$, а вторая прямая проходит через начало координат перпендикулярно плоскости $5x - 2y + 3z - 1 = 0$.

Вначале найдем координаты направляющего вектора для прямой $AB$, для этого составим матрицы (векторы-столбцы) из координат точек  $A$ и $B$, затем вычтем один вектор-столбец из другого:

In [5]:
A = Matrix([1, 2, 3])
B = Matrix([-3, 5, 0])
a1 = B - A
display(Latex(fr'\text{{ Направляющий вектор прямой }} AB\ {latex(a1.T)}'))

<IPython.core.display.Latex object>

Запишем уравнение прямой $AB$ в векторной форме:

In [6]:
x, y, z, t1 = symbols('x y z t1')
X = Matrix([x, y, z])
AB = A + t1 * a1
display(Latex(fr"""\text{{ Уравнение прямой }} AB
\ {latex(Eq(X, AB, evaluate=False))}"""))

<IPython.core.display.Latex object>

Более красивый и привычный вид система будет иметь, если составить отдельные уравнения для каждой координаты.

In [7]:
AB_sys = [Eq(X[i], AB[i]) for i in range(len(AB))]
display(Latex(fr"""\text{{Параметрические уравнения прямой }} AB
\ {latex(AB_sys)}"""))
display(*AB_sys)

<IPython.core.display.Latex object>

Eq(x, 1 - 4*t1)

Eq(y, 3*t1 + 2)

Eq(z, 3 - 3*t1)

Можно преобразовать в формулу в latex отдельные уравнения и вывести их последовательно с дополнительными пояснениями (мы просто пронумеруем уравнения).

In [8]:
display(Latex("""(1)\ {0},\ (2)\ {1},
\ (3)\ {2}""".format(*[latex(item) for item in AB_sys])))

<IPython.core.display.Latex object>

Здесь мы влспользовались методом format класса str. В строке, к которой применяется метод format отмечаются позиции, в которые нужно вставить аргументы format. Позиции для вставок отмечаются положительными целыми числами (номерами аргументов), заключенными к фигурные скобки. Один и тот же аргумент можно вставлять в несколько разных мест строки. Также можно вставлять аргументы в строку не в том порядке, в каком они идут в format, например '(1):\ {2},\ (2):\ {0},\ (3):\ {1}'.

Составим уравнение второй прямой, она проходит через точку $O(0, 0, 0)$, ее направляющим вектором является
вектор нормали к плоскости $5x - 2y + 3z - 1 = 0$, т.е. $(5, -2, 3)$.

In [9]:
t2 = Symbol('t2')
a2 = Matrix([5, -2, 3])
OC = t2 * a2
OC_sys = [Eq(X[i], OC[i]) for i in range(len(OC))]
display(Latex(fr"""\text{{Параметрические уравнения второй прямой }}
{latex(Eq(X, OC, evaluate=False))}\text{{ или }}{latex(OC_sys)}"""))

<IPython.core.display.Latex object>

Составим СЛАУ из уравнений двух этих прямых

In [22]:
SLAE1 = AB_sys + OC_sys
display(Latex(fr'\text{{СЛАУ из уравнений двух прямых }}{latex(SLAE1)}'))

<IPython.core.display.Latex object>

In [23]:
display(Latex(fr'\text{{Решение СЛАУ }}{latex(linsolve(SLAE1, x, y, z, t1, t2))}'))

<IPython.core.display.Latex object>

СЛАУ несовместна, прямые не пересекаются.

Можно проверить совместность СЛАУ с помощью теоремы Кронекера-Капелли, для этого
приведем СЛАУ к матричному виду с помощью linear_eq_to_matrix

In [12]:
A2, b2 = linear_eq_to_matrix(SLAE1, [x, y, z, t1, t2])
display(Latex(f'A_2={latex(A2)},\quad b_2 = {latex(b2)}'))

<IPython.core.display.Latex object>

Составим расширенную матрицу СЛАУ

In [13]:
A2b2 = A2.row_join(b2)
display(A2b2)

Matrix([
[1, 0, 0,  4,  0, 1],
[0, 1, 0, -3,  0, 2],
[0, 0, 1,  3,  0, 3],
[1, 0, 0,  0, -5, 0],
[0, 1, 0,  0,  2, 0],
[0, 0, 1,  0, -3, 0]])

Сравним ранги матрицы левой части и расширенной матрицы

In [14]:
A2.rank() == A2b2.rank()

False

Вывод: СЛАУ несовместна, следовательно, прямые не пересекаются.

## Пример 3.
Найти точку пересечения прямых в пространстве, если одна из них проходит через точки $A(-1,2,1)$ и $B(3,5,2)$, а вторая прямая проходит через точки $C(1, 3, 7)$ и $D(-3, 1/2, 1/2)$.

Составим параметрические уравнения $AB$:

In [15]:
A = Matrix([-1, 2, 1])
B = Matrix([3, 5, 2])
a1 = B - A
AB = A + t1 * a1
AB_sys = [Eq(X[i], AB[i]) for i in range(len(AB))]
display(*AB_sys)

Eq(x, 4*t1 - 1)

Eq(y, 3*t1 + 2)

Eq(z, t1 + 1)

Составим параметрические уравнения $CD$:

In [16]:
C = Matrix([1, 3, 7])
D = Matrix([-3, S(1) / 2, S(1) / 2])
a2 = D - C
CD = C + t2 * a2
CD_sys = [Eq(X[i], CD[i]) for i in range(len(CD))]
display(*CD_sys)

Eq(x, 1 - 4*t2)

Eq(y, 3 - 5*t2/2)

Eq(z, 7 - 13*t2/2)

Составим систему из параметрических уравнений $AB$ и $CD$:

In [17]:
SLAE2 = AB_sys + CD_sys
display(*SLAE2)

Eq(x, 4*t1 - 1)

Eq(y, 3*t1 + 2)

Eq(z, t1 + 1)

Eq(x, 1 - 4*t2)

Eq(y, 3 - 5*t2/2)

Eq(z, 7 - 13*t2/2)

Проверим, совместна ли наша СЛАУ, для этого составим матрицу левой части системы и расширенную матрицу и сравним ранги.

In [18]:
A3, b3 = linear_eq_to_matrix(SLAE2, [x, y, z, t1, t2])
A3b3 = A3.row_join(b3)
print(f'Система{" не" * (A3.rank() < A3b3.rank())} совместна')

Система совместна


Поскольку СЛАУ совместна, можем найти точку пересечения:

In [19]:
Set_t1_t2 = linsolve(SLAE2, x, y, z, t1, t2)
sol3 = Matrix(*Set_t1_t2)[:3, :]
display(Latex(fr'\text{{Точка пересечения двух прямых }}{latex(sol3.T)}'))

<IPython.core.display.Latex object>

## Пример 4.
Найти точку пересечения плоскости $3x + 4y - z + 5 = 0$ с прямой, проходящей через точку $A(-1, 0, 1)$ параллельно вектору $a(3, -2, 0)$.

Составим канонические уравнения прямой и уравнение плоскости, обединим все уравнения в одну систему и решим ее с помощью linsolve, затем выделим значения переменных $x$, $y$, $z$.

In [20]:
x, y, z, t = symbols('x y z t')
X = Matrix([x, y, z])
A = Matrix([-1, 0, 1])
a = Matrix([3, -2, 0])
SLAE_AB = [Eq(X[i], A[i] + a[i] * t) for i in range(len(A))]
display(Latex(fr'\text{{СЛАУ}}{latex(SLAE_AB)}'))
KMN = Eq(3 * x + 4 * y - z + 5, 0)
display(Latex(fr'\text{{Уравнение плоскости }}KMN\ {latex(KMN)}'))
SLAE_AB.append(KMN)
display(Latex(fr"""\text{{Точка пересечения }}
{latex(Matrix(*linsolve(SLAE_AB, x, y, z, t))[:-1, :].T)}"""))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

## Пример 5.
Составить уравнение плоскости, проходящей через начало координат, в которой лежит прямая, заданная уравнениями:
$$
\left\{\begin{matrix}
x = 3 + 2t\\
y = 2 - 3t\\
z = 5 + 2t
\end{matrix}\right.
$$

Найдем две различные точки на прямой, придавая разные значения параметру $t$, например, 0 и 1. Затем составим уравнение плоскости, проходящей через 3 точки.   

In [21]:
O = zeros(3, 1)
A = Matrix([3, 2, 5])
a = Matrix([2, -3, 2])
x, y, z, t = symbols('x y z t')
X = Matrix([x, y, z])
AB = A + t * a
M1 = AB.subs(t, 0)
M2 = AB.subs(t, 1)
display(Latex(fr"""\text{{Уравнение плоскости }}
{latex(Eq(Matrix([(P - M1).T for P in (X, M2, O)]).det(), 0))}"""))

<IPython.core.display.Latex object>

## Чтение данных из файла xlsx
Считать данные из табличного файла можно с помощью библиотеки pandas, нам понадобится функция
### pandas.read_excel
pandas.read_excel(io, sheet_name=0, header=0, names=None, index_col=None, usecols=None, squeeze=False, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, parse_dates=False, date_parser=None, thousands=None, comment=None, skipfooter=0, convert_float=True, mangle_dupe_cols=True, storage_options=None)

Подробности смотрите здесь:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html


## Пример 6
Прочитать координаты точек в пространстве из файла 'points.xlsx' и вывести их на экран.

Рекомендуется открыть файл и посмотреть на содержимое. Обратите внимание, что в таблице есть названия строк и столбцов, сами эти названия не являются данными.

Для загрузки файла в среду colab.research нам понадобится импортировать модуль files и pandas

In [24]:
from google.colab import files
import pandas as pd

Загружаем файл программно

In [25]:
uploaded = files.upload() # загружаем нужные файлы, обращаться к ним будем по имени

Saving points.xlsx to points.xlsx


При запуске кода ячейки в файловой системе выбираем нужный файл, он загружается в виртуальное сессионное хранилище.

Считываем данные и выводим их на экран.

In [37]:
points_table = pd.read_excel('points.xlsx', index_col=0)
print(points_table)

    x   y   z
A  29   7   2
B  85  90  58
C  39  66  47
D  29  37  34
E  20   4  37
F  53  26  71
G  21  53  98
H  74  38  98
K  59  33  17
M  65  93  63


Прочитались не только координаты точек, но и названия точек и координат. Выделим все отдельно и запишем в разные переменные.

In [44]:
points_coords = points_table.to_numpy()
points_names = points_table.index
coords_names = points_table.columns
print(f'points_names: {points_names}',
      f'coords_names: {coords_names}',
      f'points_coords:\n{points_coords}', sep='\n')

points_names: Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'K', 'M'], dtype='object')
coords_names: Index(['x', 'y', 'z'], dtype='object')
points_coords:
[[29  7  2]
 [85 90 58]
 [39 66 47]
 [29 37 34]
 [20  4 37]
 [53 26 71]
 [21 53 98]
 [74 38 98]
 [59 33 17]
 [65 93 63]]


In [41]:
for point_name, coords in zip(points_names, points_coords):
    x, y, z = coords
    print(f'{point_name}({x}, {y}, {z})')

A(29, 7, 2)
B(85, 90, 58)
C(39, 66, 47)
D(29, 37, 34)
E(20, 4, 37)
F(53, 26, 71)
G(21, 53, 98)
H(74, 38, 98)
K(59, 33, 17)
M(65, 93, 63)
