# Практическое занятие 8
# Компьютерный практикум по алгебре на Python
## Численное решение систем линейных алгебраических уравнений (СЛАУ) с numpy.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [ ]:
import numpy as np
from numpy import linalg
from google.colab import files
import pandas as pd

### Задание 1.
Решить СЛАУ с помощью linalg.solve() и выполнить проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+4y+3z=18\\
5x-y+4z=81\\
-3x+5y+5z=21
\end{matrix}
\right.
$$

In [ ]:
A = np.array([[-1, 4, 3],
              [5, -1, 4],
              [-3, 5, 5]])
b = np.array([18,81,21])
X = linalg.solve(A,b)
display(X)
display(A @ X == b)
display(np.allclose(A @ X, b))

array([ 8., -1., 10.])

array([False,  True, False])

True

### Задание 2.
Определить с помощью Теоремы Кронекера-Капелли и linalg.matrix_rank, совместны ли СЛАУ
$$
a)\ \left\{
\begin{matrix}
-x + 4y + 3z = 18\\
5x - y + 4z = 81\\
8x - 13y - 5z = 2
\end{matrix}
\right.
b)\ \left\{
\begin{matrix}
-x + 4y + 3z = 18\\
5x - y + 4z = 81\\
8x - 13y - 5z = 27
\end{matrix}
\right.
c)\ \left\{
\begin{matrix}
-x + 4y + 3z = 18\\
5x - y + 4z = 81\\
8x - 13y - z = 27
\end{matrix}
\right.
$$

Сделать вывод о числе решений каждой СЛАУ (текстом)

In [ ]:
a1 = np.array((
      (-1, 4, 3),
      (5, -1, 4),
      (8, -13, -5),
  ))
b1 = np.array([18, 81, 2])
ab1 = np.column_stack((a1, b1))
display(f"Ранг rk(А) = {linalg.matrix_rank(a1)}")
display(f"Ранг rk(Аb) = {linalg.matrix_rank(ab1)}")
if linalg.matrix_rank(a1) == linalg.matrix_rank(ab1):
    display('СЛАУ совместна')
    display('Матрица имеет ' +'1 решение' if a1.shape[1] == linalg.matrix_rank(a1) else 'бесконечно много решений')
else:
  display('СЛАУ несовместна')
print()
a2 = np.array((
      (-1, 4, 3),
      (5, -1, 4),
      (8, -13, -5),
  ))
b2 = np.array([18, 81, 27])
ab2 = np.column_stack((a2, b2))
display(f"Ранг rk(А) = {linalg.matrix_rank(a2)}")
display(f"Ранг rk(Аb) = {linalg.matrix_rank(ab2)}")
if linalg.matrix_rank(a2) == linalg.matrix_rank(ab2):
    display('СЛАУ совместна')
    display('Матрица имеет ' +'1 решение' if a2.shape[1] == linalg.matrix_rank(a2) else 'бесконечно много решений')
else:
  display('СЛАУ несовместна')
print()

a3 = np.array((
      (-1, 4, 3),
      (5, -1, 4),
      (8, -13, -1),
  ))
b3 = np.array([18, 81, 27])
ab3 = np.column_stack((a3, b3))
display(f"Ранг rk(А) = {linalg.matrix_rank(a3)}")
display(f"Ранг rk(Аb) = {linalg.matrix_rank(ab3)}")
if linalg.matrix_rank(a3) == linalg.matrix_rank(ab3):
    display('СЛАУ совместна')
    display('Матрица имеет ' +'1 решение' if a3.shape[1] == linalg.matrix_rank(a3) else 'бесконечно много решений')
else:
  display('СЛАУ несовместна')

'Ранг rk(А) = 2'

'Ранг rk(Аb) = 3'

'СЛАУ несовместна'

'Ранг rk(А) = 2'

'Ранг rk(Аb) = 2'

'СЛАУ совместна'

'бесконечно много решений'

'Ранг rk(А) = 3'

'Ранг rk(Аb) = 3'

'СЛАУ совместна'

'Матрица имеет 1 решение'

### Задание 3
Описать функцию print_info с обязательным аргументом **$Ab$** - расширенной матрицей СЛАУ и необязательным аргументом  **end** (по умолчанию "\n", его нужно передавать функции print как ее  необязательный аргумент end), выводящую на экран

1) матрицу левой части СЛАУ

2) столбец правой части СЛАУ

3) транспонированную матрицу, полученную в 1)

4) расширенную матрицу, полученную из матрицы 3) и столбца 2)

5) созданную на основе списочного выражения np.array $3\times 4$ из расположенных в шахматном порядке чисел $a$ и $-a$, где $a$ - правый нижний элемент матрицы 3).

Применить полученную функцию к расширенным матрицам СЛАУ из Задания 2 со значением **end="\\n\\n"**, а затем  **end** по умолчанию.

In [ ]:
def print_info(Ab, end='\n'):
  A = np.array([x[:-1] for x in Ab])
  b = np.array([[x[-1]] for x in Ab])
  aT = np.transpose(A)
  C = np.column_stack((aT,b))
  a = aT[-1][-1]
  chess_mat = []
  for i in range(3):
    temp = []
    for j in range(4):
      temp += [a if (i+j) % 2 == 0 else -a]
    chess_mat.append(temp)
  chess_mat = np.array(chess_mat)
  print(A, end = end)
  print(b, end = end)
  print(aT, end = end)
  print(C, end = end)
  print(chess_mat, end = end)

print('A)')
print_info(ab1,end ='\n\n')
print('B)')
print_info(ab2, end = '\n\n')
print('C)')
print_info(ab3, end = '\n\n')


print('A)')
print_info(ab1)
print('B)')
print_info(ab2)
print('C)')
print_info(ab3)

A)
[[ -1   4   3]
 [  5  -1   4]
 [  8 -13  -5]]

[[18]
 [81]
 [ 2]]

[[ -1   5   8]
 [  4  -1 -13]
 [  3   4  -5]]

[[ -1   5   8  18]
 [  4  -1 -13  81]
 [  3   4  -5   2]]

[[-5  5 -5  5]
 [ 5 -5  5 -5]
 [-5  5 -5  5]]

B)
[[ -1   4   3]
 [  5  -1   4]
 [  8 -13  -5]]

[[18]
 [81]
 [27]]

[[ -1   5   8]
 [  4  -1 -13]
 [  3   4  -5]]

[[ -1   5   8  18]
 [  4  -1 -13  81]
 [  3   4  -5  27]]

[[-5  5 -5  5]
 [ 5 -5  5 -5]
 [-5  5 -5  5]]

C)
[[ -1   4   3]
 [  5  -1   4]
 [  8 -13  -1]]

[[18]
 [81]
 [27]]

[[ -1   5   8]
 [  4  -1 -13]
 [  3   4  -1]]

[[ -1   5   8  18]
 [  4  -1 -13  81]
 [  3   4  -1  27]]

[[-1  1 -1  1]
 [ 1 -1  1 -1]
 [-1  1 -1  1]]

A)
[[ -1   4   3]
 [  5  -1   4]
 [  8 -13  -5]]
[[18]
 [81]
 [ 2]]
[[ -1   5   8]
 [  4  -1 -13]
 [  3   4  -5]]
[[ -1   5   8  18]
 [  4  -1 -13  81]
 [  3   4  -5   2]]
[[-5  5 -5  5]
 [ 5 -5  5 -5]
 [-5  5 -5  5]]
B)
[[ -1   4   3]
 [  5  -1   4]
 [  8 -13  -5]]
[[18]
 [81]
 [27]]
[[ -1   5   8]
 [  4  -1 -13]
 [  3   4  -5]]

### Задание 4.
Исследовать на совместность СЛАУ с параметром $a$ при значениях параметра $a=-1$, $a=0$ и $a=1$ и найти решение, если оно единственно и провести проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+5y-3z=8a\\
4x-ay+5z=-a\\
3x+4y+2z=5a
\end{matrix}
\right.
$$
**Указание** - описать функцию check_SLAE от аргументов $A$ и $b$ (матрица левой части и столбец правой части), которая возвращает 0 для несовместной СЛАУ, 1 для совместной СЛАУ с единственным решением и 2 в остальных случаях.

Затем в цикле по значениям параметра $a$ проверять с помощью check_SLAE совместность и единственность решения СЛАУ и выводить на экран значение параметра и решение СЛАУ, если оно существует и единственно или "решений нет" или "решение не единственно".

In [ ]:
def solve(a: int):
  a_matrix = np.array((
    (-1, 5, -3),
    (4, -a, 5),
    (3, 4, 2),
  ))
  b_matrix = np.array([8*a, -a, 5*a])
  ab_matrix = np.column_stack((a_matrix, b_matrix))

  display('При a равен ' + str(a) + ':')
  rk_a = linalg.matrix_rank(a_matrix)
  rk_ab = linalg.matrix_rank(ab_matrix)
  if rk_a == rk_ab:
    display('Матрица имеет решения')
    if a_matrix.shape[1] == rk_a:
      display('Матрица имеет единственное решение:')
      display(linalg.solve(a_matrix, b_matrix))
    else:
      display('Матрица имеет более 1 решения')
  else:
    display('Матрица не имеет решений')
  print()

for a in (-1,0, 1):
    solve(a)

'При a равен -1:'

'Матрица имеет решения'

'Матрица имеет единственное решение:'

array([-1.28571429, -1.        ,  1.42857143])

'При a равен 0:'

'Матрица имеет решения'

'Матрица имеет единственное решение:'

array([ 0.,  0., -0.])

'При a равен 1:'

'Матрица не имеет решений'

### Задание 5.
Считать из файла 'SLAE_5.xlsx' матрицу левой части и столбец правой части с листов 'A5' и 'b5' и вывести их на экран.

Решить СЛАУ $AX=b$ и вывести полученное решение на экран.

Записать полученное решение в файл  'SLAE_5.xlsx' на лист 'X5'.

Скачать полученный файл.

In [ ]:
file_name = 'SLAE_5.xlsx'

Adf = pd.read_excel(file_name, sheet_name='A5', header=None)
bdf = pd.read_excel(file_name, sheet_name='b5', header=None)
A = np.array(Adf.values)
b = np.array(bdf.values)
Ab = np.column_stack((A,b))
print(A)
print(b)
X = linalg.solve(A,b)
print(X)
Xdf = pd.DataFrame(X)

with pd.ExcelWriter(file_name, mode='a') as writer:
    Xdf.to_excel(writer, sheet_name='X5', header=False, index=False)
files.download(file_name)

[[ -1   6   9  -1  -3  -8   9   9   1   6  -3   1   6  -3  -2   6   6  -7]
 [  3   5   0   8   3  -1 -10   9 -10   3  -9  -1   5   9   8  -9  -7   5]
 [  4   2  -3  -4  -9   3   9   5  -4   8  -4   1 -10   9  -3  -6  -5  -4]
 [ -7  -9  -5   4   3  -6  -6   7 -10   0   3  -7  -4  -7 -10   8   9   0]
 [  9  -1   7   9  -8  -2   6   0   3   3  -3  -3  -8  -6  -6  -7   2   0]
 [ -3   0   3   1  -6 -10  -8  -9  -7   7   6   6   1 -10   6  -7   6   1]
 [ -1  -6   8  -1   1  -7 -10   7 -10   3   2   6   2   0  -1 -10   6   3]
 [ -6  -5  -6   5   5  -7   0  -8   3  -2  -7  -2   0   1  -5  -4  -9  -9]
 [ -8   2  -8   9  -3   5  -5  -6   1   7   8  -3   1   6  -5   6   9  -2]
 [ -7   7   2  -9   4  -4  -8  -7   4   1  -9   9  -5   5  -6   4   2   0]
 [ -2  -2   7 -10  -3  -5 -10   8  -6   2  -9   1  -2   2  -3  -6  -5  -4]
 [  8  -2  -5 -10  -1  -2   8  -5  -1   7  -5   1   1 -10  -4   2   0  -5]
 [  1   4  -8 -10  -1   2   1   0   3   2   0   1   9  -8  -2  -5   5  -8]
 [ -3  -2   9   0  -7   3

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

### Индивидуальное задание.
Исследовать на совместность СЛАУ с параметром $a$ при заданных значениях параметра $a$ и найти решение, если оно единственно и провести проверку подстановкой.

На листы 'A1', 'A2' и т.п. файла 'Name_Ind_8_SLAE.xlsx' записать матрицы при заданных значениях параметра $a$, на листы 'b1', 'b2' и т.п. столбцы правой части СЛАУ, на листы 'X1', 'X2' и т.п. решения СЛАУ (если оно существует!).


In [ ]:
!pip install xlsxwriter
file_name = 'Name_Ind_8_SLAE.xlsx'
count = 1
writer = pd.ExcelWriter(file_name, engine='xlsxwriter')
for a in (-2,2,6):
  a_matrix = np.array((
      (1, a, 3, 4),
      (2, 4, 4, 2),
      (1, 3, 2, 4),
      (4, 3, 3, 1)
  ))
  b_column = np.array([4, -4, a, -4])
  ab_matrix = np.column_stack((a_matrix, b_column))

  print(f"При a = {a}:")
  rk_a = linalg.matrix_rank(a_matrix)
  rk_ab = linalg.matrix_rank(ab_matrix)
  print(f"Ранг rk(A) = {rk_a}.\tРанг rk(Ab) = {rk_ab}")
  flag = 0

  if rk_a != rk_ab:
    print("СЛАУ несовместна\n")
  elif a_matrix.shape[1] != rk_a:
    print("СЛАУ имеет более 1 решения\n")
  else:
    print("СЛАУ имеет 1 решение:")
    print(linalg.solve(a_matrix, b_column))
    flag = 1
  Adf = pd.DataFrame(a_matrix)
  bdf = pd.DataFrame(b_column)

  Adf.to_excel(writer, sheet_name='A' + str(count), header=False, index=False)
  bdf.to_excel(writer, sheet_name='b' + str(count), header=False, index=False)
  if flag == 1:
    X = linalg.solve(a_matrix, b_column)
    Xdf = pd.DataFrame(X)
    Xdf.to_excel(writer, sheet_name='X' + str(count), header=False, index=False)
  count+=1
writer.close()
files.download(file_name)

При a = -2:
Ранг rk(A) = 4.	Ранг rk(Ab) = 4
СЛАУ имеет 1 решение:
[-0.32183908 -1.17241379  0.13793103  0.3908046 ]
При a = 2:
Ранг rk(A) = 4.	Ранг rk(Ab) = 4
СЛАУ имеет 1 решение:
[ 0. -2. -0.  2.]
При a = 6:
Ранг rk(A) = 4.	Ранг rk(Ab) = 4
СЛАУ имеет 1 решение:
[ 0.12121212  0.18181818 -2.54545455  2.60606061]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>